### PR TITLE
Feat(CORS Support)

### LINKED ISSUE #334: Add crossorigin attribute to preconnect links
Without specifying a `crossorigin` attribute on preconnect links, browsers will only do a DNS prefetch rather than actually connecting to the resource.

```html
<link href="..." rel="preconnect" crossorigin>
```

### PR DESCRIPTION
**Pull request by schnogz**
Resolves #334 
Adds `crossorigin` attribute by default and allows for further CORS customization as desired by user.

### CODE REVIEW

**Comment by NoriSte** [comment]
Thanks @schnogz , I'll reivew and merge it in the next few days!

**Comment by NoriSte** [comment]
Hi @schnogz, sorry tor the big delay. Well:
- I adjusted the duplicate settings removal (that could not be effective anymore with objects instead of strings)
- the plugin now accepts true, false, '', 'anonymous', and 'use-credentials' as crossOrigin values
- I added some unit tests to the new utilities

Let me know what do you think 😊

**Comment by schnogz** [comment]
LGTM 👍

**Comment by NoriSte** [comment]
At the beginning I wanted to:
- crossOrigin set to `undefined` (default to `true`)
generates a <link rel="preconnect" href="https://example.com" **crossorigin**>
- crossOrigin set to `true`
generates a <link rel="preconnect" href="https://example.com" **crossorigin**>
- crossOrigin set to `false`
generates a <link rel="preconnect" href="https://example.com">
- crossOrigin set to `anonymous`
generates a <link rel="preconnect" href="https://example.com" **crossorigin**>
- crossOrigin set to `use-credentials`
generates a <link rel="preconnect" href="https://example.com" **crossorigin="use-credentials"**>

But... I had a problem with 
```js
React.createElement('link', {
      rel: "preconnect",
      href: domain,
      key: domain,
     crossorigin: crossOrigin
    })
```
that, when `crossOrigin` is set to `true`, it does not add the `crossorigin` attribute without any value... even if React adds it as expected (I know how React works and [this CodeSandbox](https://codesandbox.io/s/element-attribute-boolean-u26gi) demonstrates it) but I run out of time and I moved to the generation of

<link rel="preconnect" href="https://example.com" **crossorigin=""**>

instead of

<link rel="preconnect" href="https://example.com" **crossorigin**>
...

Any clues? Am I missing any stupid things? 🤔

**Comment by NoriSte** [comment]
Found the problem: in case of the script above, React gets `Warning: Received 'true' for a non-boolean attribute 'crossOrigin'` 😉

**Comment by NoriSte** [comment]
@all-contributors please add @seaneking for ideas

**Comment by NoriSte** [comment]
@all-contributors please add @schnogz for code, doc, and test

**Comment by NoriSte** [comment]
@all-contributors please add @schnogz for code, doc, and test

**Pull request merged**
